export interface ServiceCategory {
  id: string;
  name: string;
  description: string;
  aiScore: number;
  icon: string;
  subcategories: string[];
  color: "blue" | "green" | "red" | "orange" | "purple" | "pink" | "cyan" | "lime";
}

export interface CategoryGroup {
  groupName: string;
  groupIcon: string;
  categories: ServiceCategory[];
}

export const categoryGroups: CategoryGroup[] = [
  {
    groupName: "Ev & Yaşam Hizmetleri",
    groupIcon: "🏠",
    categories: [
      {
        id: "ev-temizligi",
        name: "Ev Temizliği",
        description: "Profesyonel ev temizliği hizmeti",
        aiScore: 92,
        icon: "🧹",
        color: "blue",
        subcategories: [
          "Günlük Temizlik",
          "Derin Temizlik",
          "Halı Yıkama",
          "Camların Temizlenmesi",
        ],
      },
      {
        id: "boya-badana",
        name: "Boya Badana",
        description: "İç dış boya ve badana işleri",
        aiScore: 89,
        icon: "🎨",
        color: "orange",
        subcategories: [
          "İç Boya",
          "Dış Boya",
          "Dekoratif Boya",
          "Ahşap Boyama",
        ],
      },
      {
        id: "ev-tadilati",
        name: "Ev Tadilatı",
        description: "Dar alanlar ile tam renovasyon",
        aiScore: 88,
        icon: "🔨",
        color: "red",
        subcategories: [
          "Kısmi Tadilat",
          "Tam Renovasyon",
          "Mutfak Tadilatı",
          "Banyo Tadilatı",
        ],
      },
      {
        id: "tesisatci",
        name: "Tesisat Tamiri",
        description: "Su ve ısıtma tesisat hizmetleri",
        aiScore: 91,
        icon: "🔧",
        color: "green",
        subcategories: [
          "Oto Tesisat",
          "Yeni Tesisat Kurulumu",
          "Su Kaçağı Tespiti",
          "Musluk Tamiri",
        ],
      },
      {
        id: "elektrikci",
        name: "Elektrikçi",
        description: "Elektrik kurulum ve tamiri",
        aiScore: 93,
        icon: "⚡",
        color: "cyan",
        subcategories: [
          "Aydınlatma Kurulumu",
          "Panel Tamiri",
          "Tesisat Yenileme",
          "Acil Elektrik",
        ],
      },
      {
        id: "beyaz-esya",
        name: "Beyaz Eşya Tamiri",
        description: "Tüm beyaz eşya tamiri ve servisi",
        aiScore: 87,
        icon: "❄️",
        color: "purple",
        subcategories: [
          "Buzdolabı Tamiri",
          "Çamaşır Makinesi",
          "Iyiyaştırıcı Tamiri",
          "Oven Tamiri",
        ],
      },
      {
        id: "klima",
        name: "Klima Temizliği & Servisi",
        description: "Klima kurulum, bakım ve tamiri",
        aiScore: 90,
        icon: "❄️",
        color: "blue",
        subcategories: [
          "Klima Montajı",
          "Klima Temizliği",
          "Freon Dolumu",
          "Klima Tamiri",
        ],
      },
      {
        id: "kombi",
        name: "Kombi Bakım & Tamiri",
        description: "Doğal gaz ve elektrik kombi hizmetleri",
        aiScore: 89,
        icon: "🔥",
        color: "red",
        subcategories: [
          "Kombi Kurulumu",
          "Servis ve Bakım",
          "Kombi Tamiri",
          "Enerji Verimliliği",
        ],
      },
      {
        id: "mobilya-montaji",
        name: "Mobilya Montajı",
        description: "Tüm mobilya öğeleri montaj hizmeti",
        aiScore: 85,
        icon: "🪑",
        color: "orange",
        subcategories: [
          "Dolap Montajı",
          "Kanepe Montajı",
          "Yatak Montajı",
          "Raf Kurulumu",
        ],
      },
      {
        id: "bock-ilaclamasi",
        name: "Böcek İlaçlama",
        description: "Profesyonel haşere kontrol ve ilaçlama",
        aiScore: 88,
        icon: "🪲",
        color: "green",
        subcategories: [
          "Sinek Kontrol",
          "Hamamböceği Kontrol",
          "Haşere Taraması",
          "Koruma Sözleşmesi",
        ],
      },
      {
        id: "cati-tamiri",
        name: "Çatı Tamiri",
        description: "Çatı sızıntıları ve tamir işleri",
        aiScore: 86,
        icon: "🏘️",
        color: "pink",
        subcategories: [
          "Çatı Taraması",
          "Sızıntı Tespiti",
          "Çatı Yenileme",
          "Mansard Kurulumu",
        ],
      },
    ],
  },
  {
    groupName: "Tadilat & İnşaat",
    groupIcon: "🔨",
    categories: [
      {
        id: "insaat-ustasi",
        name: "İnşaat Ustası",
        description: "Genel inşaat ve yapı hizmetleri",
        aiScore: 91,
        icon: "👷",
        color: "red",
        subcategories: [
          "Duvar Örme",
          "Beton İşleri",
          "Temel Atma",
          "Demir İşleri",
        ],
      },
      {
        id: "izolasyon",
        name: "İzolasyon Hizmetleri",
        description: "Su, ısı ve ses yalıtımı",
        aiScore: 87,
        icon: "🛡️",
        color: "blue",
        subcategories: [
          "Su İzolasyonu",
          "Termal İzolasyon",
          "Ses İzolasyonu",
          "Çatı Yalıtımı",
        ],
      },
      {
        id: "zemin-kaplama",
        name: "Zemin Kaplama",
        description: "Epoksi, mermer, karo ve parke",
        aiScore: 89,
        icon: "⬜",
        color: "orange",
        subcategories: [
          "Mermer Kaplaması",
          "Karo Kaplaması",
          "Parke Döşeme",
          "Epoksi Zemin",
        ],
      },
      {
        id: "aluminyum-dograsi",
        name: "Alüminyum Doğrama",
        description: "Alüminyum pencere ve kapı kurulumu",
        aiScore: 88,
        icon: "🪟",
        color: "cyan",
        subcategories: [
          "Pencere Kurulumu",
          "Kapı Kurulumu",
          "Cam Balkon",
          "Panjur Montajı",
        ],
      },
      {
        id: "asma-tavan",
        name: "Alçıpan & Asma Tavan",
        description: "Asma tavan ve alçıpan işleri",
        aiScore: 86,
        icon: "🎪",
        color: "purple",
        subcategories: [
          "Gips Board Montajı",
          "Asma Tavan",
          "Ses Yalıtımlı Panel",
          "Led Aydınlatma Kurulumu",
        ],
      },
      {
        id: "celik-kapi",
        name: "Çelik Kapı & Pencere",
        description: "Güvenlik kapı ve pencere kurulumu",
        aiScore: 89,
        icon: "🚪",
        color: "pink",
        subcategories: [
          "Çelik Kapı Kurulumu",
          "Parmak İzi Kilit",
          "Otomatik Kapı",
          "Garaj Kapısı",
        ],
      },
      {
        id: "asansor-servisi",
        name: "Asansör Servisi",
        description: "Bina asansör bakım, arıza ve montaj hizmetleri",
        aiScore: 94,
        icon: "🛗",
        color: "cyan",
        subcategories: [
          "Asansör Bakımı",
          "Asansör Arıza Onarımı",
          "Asansör Montajı",
          "Yük Asansörü Servisi",
        ],
      },
      {
        id: "merdiven-korkusu",
        name: "Merdiven Korkuluğu",
        description: "Paslanmaz çelik ve cam korkuluk",
        aiScore: 85,
        icon: "🪜",
        color: "green",
        subcategories: [
          "Paslanmaz Çelik Korkuluk",
          "Cam Korkuluk",
          "Ahşap Korkuluk",
          "Balkon Korkuluğu",
        ],
      },
      {
        id: "dekoratif-siva",
        name: "Dekoratif Sıva",
        description: "Stüko, tunç ve dekoratif sıva",
        aiScore: 84,
        icon: "✨",
        color: "orange",
        subcategories: [
          "Stüko Sıva",
          "Tunç Sıva",
          "Duvar Kağıdı",
          "Beton Görünümlü Sıva",
        ],
      },
    ],
  },
  {
    groupName: "Araç & Taşıma",
    groupIcon: "🚗",
    categories: [
      {
        id: "oto-tamir",
        name: "Oto Tamir & Servis",
        description: "Genel otomotiv bakım ve tamiri",
        aiScore: 91,
        icon: "🔧",
        color: "blue",
        subcategories: [
          "Yağ Değişimi",
          "Fren Tamiri",
          "Motor Tamirleri",
          "Hava Filtresi",
        ],
      },
      {
        id: "oto-yikama",
        name: "Oto Yıkama",
        description: "Profesyonel araç yıkama ve cilası",
        aiScore: 87,
        icon: "💧",
        color: "cyan",
        subcategories: [
          "Standart Yıkama",
          "Detaylı Temizlik",
          "Deta Yıkama",
          "İç Temizlik",
        ],
      },
      {
        id: "lastik-degisimi",
        name: "Lastik Tamir & Değişim",
        description: "Lastik tamiri, tamiş ve hizalama",
        aiScore: 88,
        icon: "🛞",
        color: "green",
        subcategories: [
          "Lastik Tamiş",
          "Lastik Değişim",
          "Tekerlek Hizalama",
          "Balans Ayarı",
        ],
      },
      {
        id: "oto-elektrik",
        name: "Oto Elektrik",
        description: "Araç elektrik sistemi tamiri",
        aiScore: 89,
        icon: "⚡",
        color: "red",
        subcategories: [
          "Akü Değişimi",
          "Alternator Tamiri",
          "Başlangıç Motoru",
          "Aydınlatma Sistemi",
        ],
      },
      {
        id: "oto-klima",
        name: "Oto Klima Servisi",
        description: "Araç klima bakım ve tamiri",
        aiScore: 90,
        icon: "❄️",
        color: "purple",
        subcategories: [
          "Klima Servisi",
          "Freon Dolumu",
          "Kompresör Tamiri",
          "Filtre Değişimi",
        ],
      },
      {
        id: "oto-kaporta",
        name: "Oto Kaporta & Boya",
        description: "Araç boyası, kaporta ve döşeme",
        aiScore: 86,
        icon: "🎨",
        color: "orange",
        subcategories: [
          "Kaporta Tamiri",
          "Araç Boyası",
          "Korrosyon Koruması",
          "Döşeme Değişimi",
        ],
      },
      {
        id: "evden-eve-nakliyat",
        name: "Evden Eve Nakliyat",
        description: "Şehir içi ve şehirler arası taşıma",
        aiScore: 92,
        icon: "📦",
        color: "pink",
        subcategories: [
          "Şehir İçi Nakliyat",
          "Şehirler Arası",
          "Asansörlü Taşıma",
          "Paket Gönderi",
        ],
      },
      {
        id: "tasima-hizmeti",
        name: "Parça Eşya Taşıma",
        description: "Tek eşya veya az hacimli taşıma",
        aiScore: 88,
        icon: "🚚",
        color: "red",
        subcategories: [
          "Mobilya Taşıma",
          "Beyaz Eşya Taşıma",
          "Sanat Eseri Taşıma",
          "İnşaat Malzeme Taşıma",
        ],
      },
      {
        id: "depolama",
        name: "Eşya Depolama",
        description: "Güvenli eşya depolama ve saklamacılık",
        aiScore: 85,
        icon: "📦",
        color: "blue",
        subcategories: [
          "Ay Depolaması",
          "Mobilya Depolaması",
          "İmalı Klimalı Depo",
          "Sigortalı Depolama",
        ],
      },
    ],
  },
  {
    groupName: "Sağlık & Kişisel Bakım",
    groupIcon: "💅",
    categories: [
      {
        id: "kuafor-evde",
        name: "Kuaför (Evde)",
        description: "Evde saç kesim ve tasarımı",
        aiScore: 93,
        icon: "✂️",
        color: "pink",
        subcategories: [
          "Saç Kesim",
          "Saç Tasarımı",
          "Saç Boyama",
          "Fön Tasarımı",
        ],
      },
      {
        id: "manikur-pedikur",
        name: "Manikür/Pedikür",
        description: "Evde Manikür ve pedikür hizmeti",
        aiScore: 91,
        icon: "💅",
        color: "purple",
        subcategories: [
          "Manikür",
          "Pedikür",
          "Jel Manikür",
          "Tırnak Tasarımı",
        ],
      },
      {
        id: "cilt-bakimi",
        name: "Cilt Bakımı",
        description: "Profesyonel cilt bakımı hizmetleri",
        aiScore: 89,
        icon: "✨",
        color: "orange",
        subcategories: [
          "Yüz Temizliği",
          "Peeling",
          "Botoks Danışmanlığı",
          "Cilt Analizi",
        ],
      },
      {
        id: "masaj",
        name: "Masaj Terapisi",
        description: "Spor, terapötik ve rahatlama masajı",
        aiScore: 90,
        icon: "🧘",
        color: "cyan",
        subcategories: [
          "Klasik Masaj",
          "Spor Masajı",
          "Terapi Masajı",
          "Refleksologia",
        ],
      },
      {
        id: "fizyoterapist",
        name: "Fizyoterapist",
        description: "Evde fizyoterapistik tedavi",
        aiScore: 88,
        icon: "🏥",
        color: "green",
        subcategories: [
          "Bel Ağrısı Tedavisi",
          "Boyun Ağrısı Tedavisi",
          "Rehabihitasyon",
          "Kas Güçlendirme",
        ],
      },
      {
        id: "psikolog",
        name: "Psikolog / Terapist",
        description: "Online ve ofis danışmanlık",
        aiScore: 87,
        icon: "💭",
        color: "blue",
        subcategories: [
          "Online Terapist",
          "Ofis Danışmanlık",
          "Çift Terapisi",
          "Çocuk Psikoloji",
        ],
      },
      {
        id: "diyetisyen",
        name: "Diyetisyen",
        description: "Beslenme danışmanlığı ve diyet planı",
        aiScore: 86,
        icon: "🥗",
        color: "green",
        subcategories: [
          "Kişiselleştirilmiş Diyet",
          "Spor Beslenme Danışması",
          "Sağlık Koçluğu",
          "Beslenme Eğitimi",
        ],
      },
      {
        id: "eves-saglik",
        name: "Evde Sağlık Hizmeti",
        description: "Hemşire ve sağlık bakıcısı",
        aiScore: 92,
        icon: "🚑",
        color: "red",
        subcategories: [
          "Bakıci Hizmeti",
          "Hemşire Hizmeti",
          "Enjeksiyon",
          "Esas Bakım",
        ],
      },
      {
        id: "bebek-cocuk-bakicisi",
        name: "Bebek & Çocuk Bakıcısı",
        description: "Evde bebek ve çocuk bakım desteği",
        aiScore: 93,
        icon: "🍼",
        color: "pink",
        subcategories: [
          "Bebek Bakıcısı",
          "Çocuk Bakıcısı",
          "Oyun Ablası",
          "Yeni Doğan Bakımı",
        ],
      },
    ],
  },
  {
    groupName: "Eğitim & Danışmanlık",
    groupIcon: "📚",
    categories: [
      {
        id: "ozel-ders",
        name: "Özel Ders",
        description: "Matematika, İngilizce, Müzik vb.",
        aiScore: 94,
        icon: "📖",
        color: "blue",
        subcategories: [
          "Matematik Dersleri",
          "İngilizce Dersleri",
          "Piyano Dersleri",
          "Keman Dersleri",
        ],
      },
      {
        id: "direksiyon-dersi",
        name: "Direksiyon Dersi",
        description: "Sürücü eğitimi ve pratik",
        aiScore: 91,
        icon: "🚗",
        color: "orange",
        subcategories: [
          "Temel Sürücü Kursu",
          "Pratik Ders",
          "Sınavı Hazırlık",
          "İleri Sürüş",
        ],
      },
      {
        id: "hukuk-danismanligi",
        name: "Hukuk Danışmanlığı",
        description: "Boşanma, miras, iş hukuku",
        aiScore: 93,
        icon: "⚖️",
        color: "purple",
        subcategories: [
          "Boşanma Danışması",
          "Miras Danışması",
          "İş Hukuku",
          "Ceza Müdafaası",
        ],
      },
      {
        id: "muhasebe-danismanligi",
        name: "Muhasebe & Mali Müşavirlik",
        description: "Muhasebe ve vergi danışmanlığı",
        aiScore: 90,
        icon: "💼",
        color: "green",
        subcategories: [
          "Mali Müşavirlik",
          "Muhasebe Hizmetleri",
          "Vergi Danışması",
          "Bağımsız Mal Emekli.",
        ],
      },
      {
        id: "isletme-danismanligi",
        name: "İşletme Danışmanlığı",
        description: "Yeni işletme kurma rehberi",
        aiScore: 88,
        icon: "📊",
        color: "pink",
        subcategories: [
          "İş Kurma Danışması",
          "Pazarlama Planı",
          "Finansal Planlama",
          "İş Modeli Geliştirme",
        ],
      },
      {
        id: "kariyer-danismanligi",
        name: "Kariyer Danışmanlığı",
        description: "Konumlanma ve iş bulma yardımı",
        aiScore: 87,
        icon: "🎯",
        color: "cyan",
        subcategories: [
          "CV Yazımı",
          "Niyet Yazısı",
          "İnsan Kaynakları Koçluğu",
          "Mülakataz Hazırlık",
        ],
      },
      {
        id: "yazilim-egitimi",
        name: "Yazılım & Teknoloji Eğitimi",
        description: "Coding, web, ve mobilya eğitimi",
        aiScore: 89,
        icon: "💻",
        color: "blue",
        subcategories: [
          "Python Programlama",
          "Web Development",
          "Mobile Uygulamalar",
          "Data Science",
        ],
      },
      {
        id: "bahasa-kursu",
        name: "Dil Kursu",
        description: "İngilizce, Almanca, Fransa vb.",
        aiScore: 91,
        icon: "🗣️",
        color: "red",
        subcategories: [
          "İngilizce Kursu",
          "Almanca Kursu",
          "İspanyolca Kursu",
          "Çin Dili Kursu",
        ],
      },
    ],
  },
  {
    groupName: "Dijital & Teknoloji",
    groupIcon: "💻",
    categories: [
      {
        id: "bilgisayar-tamir",
        name: "Bilgisayar Tamiri",
        description: "Laptop ve desktop tamiri",
        aiScore: 92,
        icon: "🖥️",
        color: "blue",
        subcategories: [
          "Donanım Tamiri",
          "SSD Kurulumu",
          "RAM GeleştiĖrme",
          "Soğutma Sistem Temiri",
        ],
      },
      {
        id: "telefon-tamir",
        name: "Telefon Tamiri",
        description: "Akıllı telefon tamiri ve bakımı",
        aiScore: 93,
        icon: "📱",
        color: "pink",
        subcategories: [
          "Ekran Değişimi",
          "Batarya Değişimi",
          "Şarj Giriş Tamiri",
          "Su Hasarı Tamiri",
        ],
      },
      {
        id: "web-tasarim",
        name: "Web Tasarım",
        description: "İnternet sitesi tasarımı",
        aiScore: 90,
        icon: "🌐",
        color: "cyan",
        subcategories: [
          "Responsive Tasarım",
          "E-ticaret Siteleri",
          "WordPress Kurulum",
          "UI/UX Tasarımı",
        ],
      },
      {
        id: "grafik-tasarim",
        name: "Grafik Tasarım",
        description: "Logo, sunum ve görsel tasarım",
        aiScore: 89,
        icon: "🎨",
        color: "orange",
        subcategories: [
          "Logo Tasarımı",
          "Sosyal Medya Grafikleri",
          "Sunum Tasarımı",
          "Baskı Türleri",
        ],
      },
      {
        id: "video-edit",
        name: "Video Editing",
        description: "Video kurma ve post-prodüksiyon",
        aiScore: 88,
        icon: "🎬",
        color: "purple",
        subcategories: [
          "Video Kurma",
          "Renkendirme",
          "Efekt Ekleme",
          "Ses Tasarımı",
        ],
      },
      {
        id: "sosyal-medya",
        name: "Sosyal Medya Yönetimi",
        description: "İçerik yönetimi ve pazarlama",
        aiScore: 87,
        icon: "📱",
        color: "red",
        subcategories: [
          "İçerik Planlaması",
          "Profil Yönetimi",
          "Reklamcılık Yönetimi",
          "Analiz Raporu",
        ],
      },
      {
        id: "seo-pazarlama",
        name: "SEO & Dijital Pazarlama",
        description: "Arama motoru ve dijital reklam",
        aiScore: 89,
        icon: "📊",
        color: "green",
        subcategories: [
          "SEO Optimizasyonu",
          "Google Ads Yönetimi",
          "Content Marketing",
          "Email Marketing",
        ],
      },
      {
        id: "yazilim-gelistirme",
        name: "Yazılım Geliştirme",
        description: "Kustom yazılım ve uygulama",
        aiScore: 91,
        icon: "💻",
        color: "blue",
        subcategories: [
          "Web UygulamaSı",
          "Mobil Uygulama",
          "Desktop Yazılımı",
          "API Geliştirme",
        ],
      },
    ],
  },
  {
    groupName: "Kurumsal & Profesyonel",
    groupIcon: "🏢",
    categories: [
      {
        id: "temizlik-sirketi",
        name: "Temizlik Şirketi",
        description: "Kurumsal ve ofis temizliği",
        aiScore: 90,
        icon: "🧹",
        color: "blue",
        subcategories: [
          "Ofis Temizliği",
          "Fabrika Temizliği",
          "Hastane Temizliği",
          "Sistem Temizliği",
        ],
      },
      {
        id: "guvenlik-hizmeti",
        name: "Güvenlik Hizmeti",
        description: "Güvenlik görevlisi ve gözetim",
        aiScore: 91,
        icon: "👮",
        color: "red",
        subcategories: [
          "Özel Güvenlik",
          "Kamerası Gözetim",
          "VIP Korumaya",
          "Depo Gözcülüğü",
        ],
      },
      {
        id: "bahce-bakimi",
        name: "Bahçe Bakımı & Peyzaj",
        description: "Bahçe tasarımı ve bakımı",
        aiScore: 88,
        icon: "🌳",
        color: "green",
        subcategories: [
          "Çim Bakımı",
          "Paya̧ndız Tasarımı",
          "Bitki Bakımı",
          "Bahçe Mobilyası",
        ],
      },
      {
        id: "fotografci",
        name: "Fotoğrafçı & Videograf",
        description: "Etkinlik ve portre fotoğrafçılığı",
        aiScore: 89,
        icon: "📷",
        color: "orange",
        subcategories: [
          "Düğün Fotoğrafçılığı",
          "Kurumsal Fotoğraf",
          "Portre Çekim",
          "Ürün Fotoğrafçılığı",
        ],
      },
      {
        id: "dugun-organizasyon",
        name: "Düğün Organizasyon",
        description: "Düğün planlama ve yönetimi",
        aiScore: 92,
        icon: "💒",
        color: "pink",
        subcategories: [
          "Toplam Planlama",
          "Dekorasyon Tasarımı",
          "Catering Yönetimi",
          "Konuşu Yönetimi",
        ],
      },
      {
        id: "etkinlik-yonetimi",
        name: "Etkinlik Yönetimi",
        description: "Konferans ve etkinlik düzenleme",
        aiScore: 90,
        icon: "🎪",
        color: "purple",
        subcategories: [
          "Konferans Organizasyonu",
          "Müzik Festivali",
          "Kurumsal Olay",
          "Ticari Ticari Fuarı",
        ],
      },
      {
        id: "tercume",
        name: "Tercüme",
        description: "Yazılı tercüme hizmetleri",
        aiScore: 87,
        icon: "📝",
        color: "blue",
        subcategories: [
          "Belge Tercümesi",
          "Teknik Tercüme",
          "Hukuk Tercümesi",
          "Sertifika Tercümesi",
        ],
      },
      {
        id: "tercumanlik",
        name: "Tercümanlık",
        description: "Sözlü tercüme hizmetleri",
        aiScore: 88,
        icon: "🗣️",
        color: "cyan",
        subcategories: [
          "Ardışık Tercümanlik",
          "Eşzamanlı Tercümanlik",
          "Muhasebe Tercümanlığı",
          "Ticaret Tercümanlığı",
        ],
      },
    ],
  },
  {
    groupName: "Sanayi & Üretim",
    groupIcon: "🏭",
    categories: [
      {
        id: "cnc-isleme",
        name: "CNC İşleme",
        description: "CNC torna ve freze işleri",
        aiScore: 93,
        icon: "⚙️",
        color: "blue",
        subcategories: [
          "Torna İşleri",
          "Freze İşleri",
          "Presizyon Parçalar",
          "3D Tasarım",
        ],
      },
      {
        id: "kaynak-metal",
        name: "Kaynak & Metal İşleri",
        description: "Kaynak ve metal fabrikasyon",
        aiScore: 91,
        icon: "🔥",
        color: "orange",
        subcategories: [
          "Elektrik Kaynağı",
          "Gaz Kaynağı",
          "Metal Kesim",
          "Bending İşleri",
        ],
      },
      {
        id: "lazer-kesim",
        name: "Lazer Kesim",
        description: "Lazer kesim ve gravür hizmetleri",
        aiScore: 92,
        icon: "🔴",
        color: "red",
        subcategories: [
          "Metal Kesim",
          "Ahşap Kesim",
          "Akrilik Kesim",
          "Gravür Hizmetleri",
        ],
      },
      {
        id: "metal-sac",
        name: "Metal Saç İşleri",
        description: "Metal saç kalıplama ve şekillendirme",
        aiScore: 90,
        icon: "📄",
        color: "cyan",
        subcategories: [
          "Saç Metal Bending",
          "Metal Kalıplama",
          "Desen Kesiş",
          "Boyak Kaplama",
        ],
      },
      {
        id: "endus-temizlik",
        name: "Endüstriyel Temizlik",
        description: "Fabrika ve endüstriyel alanlar temizliği",
        aiScore: 88,
        icon: "🧹",
        color: "green",
        subcategories: [
          "Fabrika Temizliği",
          "Makine Temizliği",
          "Yüksek Basınç Temizliği",
          "Hava Filtresi Temizliği",
        ],
      },
      {
        id: "makine-bakim",
        name: "Makine Bakım & Tamir",
        description: "Endüstriyel makine bakımı",
        aiScore: 92,
        icon: "🔧",
        color: "purple",
        subcategories: [
          "Preventif Bakım",
          "Acil Tamir",
          "Motor Tamiri",
          "Pompa Servisi",
        ],
      },
      {
        id: "kalip-tasarimi",
        name: "Kalıp Tasarım",
        description: "Kalıp tasarım ve üretimi",
        aiScore: 91,
        icon: "🎨",
        color: "pink",
        subcategories: [
          "Enjeksiyon Kalıbı",
          "Basma Kalıbı",
          "Dies Tasarımı",
          "CAD Tasarımı",
        ],
      },
      {
        id: "3d-baski",
        name: "3D Baskı",
        description: "3D modelleme ve baskı hizmetleri",
        aiScore: 89,
        icon: "🖨️",
        color: "blue",
        subcategories: [
          "Prototip Üretimi",
          "SLS Baskı",
          "FDM Baskı",
          "Tasarım Danışması",
        ],
      },
    ],
  },
  {
    groupName: "Evcil Hayvan & Niş",
    groupIcon: "🐕",
    categories: [
      {
        id: "kopek-gezdirme",
        name: "Köpek Gezdirme",
        description: "Köpek yürütme ve egzersiz",
        aiScore: 90,
        icon: "🐕",
        color: "orange",
        subcategories: [
          "Günlük Yürütme",
          "Egzersiz Saat",
          "Grup Yürütme",
          "Beslenme Hizmet",
        ],
      },
      {
        id: "pet-bakimi",
        name: "Pet Bakımı & Kuaför",
        description: "Evcil hayvan temizliği ve tımarı",
        aiScore: 89,
        icon: "🛁",
        color: "cyan",
        subcategories: [
          "İtme Yıkaması",
          "Kedi Yıkaması",
          "Tırnak Kesimi",
          "Korkunç Hizmet",
        ],
      },
      {
        id: "cicekci",
        name: "Çiçekçi / Bahçe Düzenleme",
        description: "Çiçek aranjmanı ve bahçe tasarımı",
        aiScore: 87,
        icon: "🌸",
        color: "pink",
        subcategories: [
          "Buket Aranjmanları",
          "Tören Çiçekleri",
          "İç Bitki Bakımı",
          "Terariyum Tasarımı",
        ],
      },
      {
        id: "organik-urunler",
        name: "Organik & Çevre Ürünleri",
        description: "Doğal ve organik temizlik maddeleri",
        aiScore: 85,
        icon: "🌿",
        color: "green",
        subcategories: [
          "Doğal Temizlik Ürünleri",
          "Organik Pestisitler",
          "Çevre Dostu Hizmetler",
          "Kaynak Danışması",
        ],
      },
      {
        id: "veteriner-ziyaret",
        name: "Veteriner Evde Ziyaret",
        description: "Evcil hayvan sağlık hizmetleri",
        aiScore: 91,
        icon: "🏥",
        color: "red",
        subcategories: [
          "Veteriner Ziyaret",
          "Aşılama",
          "İlaç Danışması",
          "Acil Müdahale",
        ],
      },
      {
        id: "hayvan-bakiciligi",
        name: "Evde Hayvan Bakıcılığı",
        description: "Otel tarzı evcil hayvan bakımı",
        aiScore: 88,
        icon: "🐾",
        color: "purple",
        subcategories: [
          "Köpek Pansiyon",
          "Kedi Otel",
          "Daycare Hizmet",
          "Mali Beslenme",
        ],
      },
      {
        id: "enerji-danismanligi",
        name: "Enerji Verimliliği Danışmanlığı",
        description: "Enerji tasarrufu ve verimlilik",
        aiScore: 86,
        icon: "⚡",
        color: "blue",
        subcategories: [
          "Enerji Denetim",
          "LED Dönüştürme",
          "İzolasyon Tavsiye",
          "Sertifikasyon Yardım",
        ],
      },
      {
        id: "gunestel-paneli",
        name: "Güneş Paneli Kurulumu",
        description: "Solar enerji sistem kurulumu",
        aiScore: 90,
        icon: "☀️",
        color: "orange",
        subcategories: [
          "Çatı Kurulumu",
          "Yer Kurulumu",
          "Bateri Depolama",
          "Enerji Mühendislik",
        ],
      },
    ],
  },
];

export function getCategoryById(categoryId: string): ServiceCategory | undefined {
  for (const group of categoryGroups) {
    const category = group.categories.find((c) => c.id === categoryId);
    if (category) return category;
  }
  return undefined;
}

export function getAllCategories(): ServiceCategory[] {
  return categoryGroups.flatMap((group) => group.categories);
}

export function getCategoriesCount(): number {
  return getAllCategories().length;
}
